# seed
seed: 2024 

# protein and reference ligand (preferred)
protein_fn:  data/sample/pro.pdb # data/sample/pro.pdb
receptor_fn: # data/sample/rec.pdb
# pocket (if available. if pocket is given, reference ligand is not used.)
ligand_fn: data/sample/ref.sdf

# save dirn
save_dirn: generate/sample_0/

# model dirns
model_dirn: save/public/
model_cut: best # best

# prior atom sampling
prior_atom:
  method: povme # ref, povme
  povme_train_result_fn: data/povme/sequence_split_train.csv
  povme_test_result_fn: data/povme/sequence_split_test.csv
  povme_v_sigma: 50.0 # 50.0
  povme_n_sigma: 2.0 # 2.0

# inpainting / restricted generations 
given_reference_interaction: none # none, include, exact, extracted, from_predictor
extracted_interaction_fn: # generate/final_1_morerepaint_eval/nci_top_score_0.1.pkl # ~.pt
nci_predictor_model_fn: # save_nci_predictor/240806_whole_0/ # dirn

# resampling 
repaint_iter: 4 # 4
repaint_start_step: 600 # 400, 600, 800
repaint_end_step: 1000 # 1000

# guidance terms 
bond_distance_guidance: 0.02 # 0.02
bond_angle_guidance: 0.05 # 0.05
inter_distance_guidance: 0.02 # 0.02
steric_guidance: 0.02 # 0.02

# params
bs: 5 # 10, 25, 50, 100
n_generate: 100 # number of generation per pocket
