# ablations 
abl_igen: no # if yes removes interaction generation, changes to mask

# debug
debug_data: single # single, double, 10K 
debug_data_id: 29 # if single debug, input number

recreate_directory: yes

# dirns
train_data_dirn: ./data/processed/240814_sequence/train/
valid_data_dirn: ./data/processed/240814_sequence/valid/
test_data_dirn: ./data/processed/240814_sequence/test/
save_dirn: ./save/debug/
start_model_fn: # leave emtpy, fn
start_dirn: # ./save/debug/ # leave empty, dirn 
  
# forward process params
n_timestep: 1000
h_prior: absorb_001 # uniform, absorb, marginal
e_prior: absorb_001 # uniform, absorb, marginal
i_prior: absorb_0001 # uniform, absorb, marginal
h_noise:
  schedule: advanced
  start: 0.9999
  end: 0.0001
  width: 3
x_noise:
  schedule: advanced
  start: 0.9999
  end: 0.0001
  width: 3
e_noise:
  schedule: mix
  change_timestep: 600
  noise_1:
    schedule: advanced
    start: 0.9999
    end: 0.001
    width: 3
  noise_2:
    schedule: advanced
    start: 0.001
    end: 0.0001
    width: 2
i_noise:
  schedule: mix
  change_timestep: 800
  noise_1:
    schedule: advanced
    start: 0.9999
    end: 0.001
    width: 3
  noise_2:
    schedule: advanced
    start: 0.001
    end: 0.0001
    width: 2

# model 
model:
  noise_rec_node: 0.0 # gaussian
  ## in / out dimensions
  rec_h_dim: 40
  rec_e_dim: 5
  lig_h_dim: 10
  lig_e_dim: 5
  inter_e_dim: 7
  ## model size
  hid_dim: 128
  n_layer: 6
  timestep_embd_dim: 32
  node_embd_dim: 96
  edge_embd_dim: 96
  ## regs
  dropout: 0.0
  layer_norm: yes # yes, no
  ## distance embedding
  gamma: # same as dist min
  dist_min: # if dist_min is None, neural embedding of distance will be done 
  dist_max: 
  n_step: 16
  # graph reduction
  position_reduction: sum # sum, mean
  message_reduction: sum # sum, mean, max, mul
  use_tanh: yes
  message_attention_mode: mlp # , cosine, mlp, sigmoid
  message_attention_coef: # cosine: max distance, mlp: not used, sigmoid: sigmoid center
  # distance cutoff
  rec_edge_cutoff: 6.0 # leave emtpy, float
  lig_edge_cutoff: [8.0, 4.0] # [float, float]
  inter_edge_cutoff: [10.0, 7.0] # [float, float]

# loss 
mse_train_objective: data # data, noise
weight_decay: 1.0e-16 # float
lig_h_loss: 100.0 # float 
lig_x_loss: 1.0 # float 
lig_e_loss: 100.0 # float 
inter_e_loss: 100.0 # float 
categorical_ce_loss_ratio: 0.0 # float

# train 
n_epoch: 9999 # int
bs: 64 # int 
lr: 1.0e-3 # float 
num_workers: 6 # int
clip_grad_norm: 8.0 # float 

# reduce lr on plateau
factor: 0.8 # float
patience: 10 # int
min_lr: 1.0e-5 # float

# train computation
n_gpu: 1 # int 
pre_load_dataset: yes

# validation per n epoch
n_valid: 5 # int

autocast: no
